services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dhtsearch
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dht:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.22
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
volumes:
  pgdata_dht:
  meili_data:
